
import { SignUpButton } from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import { ArrowRightIcon } from "lucide-react";
import { PricingSection } from "./_components/PricingSection";

export default function Home() {
  return <>
    
    <section className="min-h-screen flex items-center justify-center text-balance text-center flex-col gap-10 px-4" style={{
    background: `radial-gradient(circle at center,hsl(0,70%,40%,30%) 0%, hsl(0,70%,40%,30%) 40%, transparent 80%)`,
  }}>
      <h1 className="text-5xl xl:text-6xl tracking-tight font-bold">Auto Comply, Anywhere in the World!</h1>
      <p className="text-xl max-w-screen-xl"><span className="font-semibold">75%</span> of websites get privacy wrong. We make sure yours isn't one of them-with smart, region-aware legal pages handled by <span className="font-semibold">AI</span>, zero stress required.</p>
      <SignUpButton>
        <Button className="text-lg p-6 rounded-xl flex gap-2">
          Get Started for Free <ArrowRightIcon className="size-5"/>
        </Button>
      </SignUpButton>
    </section>

    <section className="py-20 px-6 text-center"style={{
    background: `radial-gradient(circle at top, #f3f4f6 0%, #ffffff 100%)`,
  }}>
      <h2 className="text-3xl font-bold mb-8">Why Auto Comply?</h2>
      <div className="grid gap-10 md:grid-cols-3 max-w-5xl mx-auto">
        <div className="bg-white p-6 rounded-xl shadow-md border">
          <h3 className="text-xl font-semibold mb-2">AI-Generated Legal Pages</h3>
          <p className="text-muted-foreground border-t pt-4">No more templates. Get smart, region-specific legal content generated by AI.</p>
        </div>
        <div className="bg-white p-6 rounded-xl shadow-md border">
          <h3 className="text-xl font-semibold mb-2">Global Compliance</h3>
          <p className="text-muted-foreground border-t pt-4">We handle policies for GDPR, CCPA, and other laws—automatically.</p>
        </div>
        <div className="bg-white p-6 rounded-xl shadow-md border">
          <h3 className="text-xl font-semibold mb-2">Zero-Stress Setup</h3>
          <p className="text-muted-foreground border-t pt-4">Integrate in minutes. Let us handle the legal side while you build.</p>
        </div>
      </div>
    </section>

    <PricingSection/>

  </>
}